# gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
java_version=21
use_datagen=true
use_access_widener=true
fabric.loom.disableRemappedVariants=true

# minecraft
minecraft_version=1.21.5
parchmentmc_version=1.21.5:2025.06.15

# mod
archives_base_name=stratagems
maven_group=com.stevekung
mod_version=0.0.1

# deps
fabric_loader_version=0.17.2
fabric_api_version=0.128.2+1.21.5
modmenu_version=14.0.0-rc.2
cloth_config_version=18.0.145