# gradle
java_version=21
use_datagen=true
use_access_widener=true
fabric.loom.disableRemappedVariants=true

# minecraft
minecraft_version=1.21.4
parchmentmc_version=1.21.4:2025.03.16

# mod
archives_base_name=stratagems
maven_group=com.stevekung
mod_version=0.0.1

# deps
fabric_loader_version=0.16.10
fabric_api_version=0.119.0+1.21.4
modmenu_version=13.0.3
cloth_config_version=17.0.144